# yaml file to produce the datasets for a campaign
# DATASET_NAME :
#   id :
#   processes :
#     - bla1
#     - bla2
#   keys :
#     - foo1
#     - foo2
#   n_files : CALC (automatic)
#   n_events : CALC (automatic)
#   destination : FILENAME


# name of the campaign to be created
campaign: run3_2022_preEE_nano_cp_tau_v12
# path of the nanoaod samples
store_path: /eos/cms/store/group/phys_higgs/HLepRare/skim_2024_v1/Run3_2022
# era
era: 2022
nanoaod: 12
postfix: preEE
# year (YR) version (nanoaod) UniqueNo (ZZ)
campaign_id: 221201

datasets_info: 
  # -------------------------------------------------- #
  # ---------------------- DATA ---------------------- #
  # -------------------------------------------------- #

  # ---------- tau dataset ---------- #

  data_tau_C:
    processes:
      - procs.data_tau
    keys:
      - /Tau_Run2022C
    aux:
      era: C
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py

  data_tau_D:
    processes:
      - procs.data_tau
    keys:
      - /Tau_Run2022D
    aux:
      era: D
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py


  # ---------- mu dataset ---------- #

  data_single_mu_C:
    processes:
      - procs.data_mu
    keys:
      - /SingleMuon_Run2022C
    aux:
      era: C
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py

  data_mu_C:
    processes:
      - procs.data_mu
    keys:
      - /Muon_Run2022C
    aux:
      era: C
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py

  data_mu_D:
    processes:
      - procs.data_mu
    keys:
      - /Muon_Run2022D
    aux:
      era: D
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py


  # ------------ e dataset ------------- #

  data_e_C: 
    processes:
      - procs.data_e
    keys:
      - /EGamma_Run2022C
    aux:
      era: C
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py

  data_e_D:
    processes:
      - procs.data_e
    keys:
      - /EGamma_Run2022D
    aux:
      era: D
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py



  # -------------------------------------------------- #
  # ----------------------- DY ----------------------- #
  # -------------------------------------------------- #

  # -----> Low Mass
  dy_lep_m10to50_madgraph:
    processes:
      - procs.dy_lep_m10to50
    keys:
      - /DYto2L_M-10to50_madgraphMLM
    dest: dy.py

  # -----> M50-LO-inclusive
  dy_lep_m50_madgraph:
    processes:
      - procs.dy_lep_m50
    keys:
      - /DYto2L_M-50_madgraphMLM
      - /DYto2L_M-50_madgraphMLM_ext1
    dest: dy.py

  # -----> M50-NLO-inclusive
  #dy_lep_m50_amcatnlo:
  #  processes:
  #    - procs.dy_lep_m50
  #  keys:
  #    - /DYto2L_M-50_amcatnloFXFX
  #  dest: dy.py

  # -----> jet binned LO
  #dy_lep_m50_1j_madgraph:
  #  processes:
  #    - procs.dy_lep_m50_1j
  #  keys:
  #    - /DYto2L_M-50_1J_madgraphMLM
  #  dest: dy.py

  #dy_lep_m50_2j_madgraph:
  #  processes:
  #    - procs.dy_lep_m50_2j
  #  keys:
  #    - /DYto2L_M-50_2J_madgraphMLM
  #  dest: dy.py

  #dy_lep_m50_3j_madgraph:
  #  processes:
  #    - procs.dy_lep_m50_3j
  #  keys:
  #    - /DYto2L_M-50_3J_madgraphMLM
  #  dest: dy.py

  #dy_lep_m50_4j_madgraph:
  #  processes:
  #    - procs.dy_lep_m50_4j
  #  keys:
  #    - /DYto2L_M-50_4J_madgraphMLM
  #  dest: dy.py

  # -------------------------------------------------- #
  # ----------------------- WJ ----------------------- #
  # -------------------------------------------------- #

  wj_incl_madgraph:
    processes:
      - procs.w_lnu
    keys:
      - /WtoLNu_madgraphMLM
      - /WtoLNu_madgraphMLM_ext1
    dest: wj.py

  wj_incl_amcatnlo:
    processes:
      - procs.w_lnu
    keys:
      - /WtoLNu_amcatnloFXFX
    dest: wj.py

  # -------------------------------------------------- #
  # ----------------------- VV ----------------------- #
  # -------------------------------------------------- #

  ww:
    processes:
      - procs.ww
    keys:
      - /WW
    dest: vv.py
    
  wz:
    processes:
      - procs.wz
    keys:
      - /WZ
    dest: vv.py

  zz:
    processes:
      - procs.zz
    keys:
      - /ZZ
    dest: vv.py


  # -------------------------------------------------- #
  # ----------------------- TT ----------------------- #
  # -------------------------------------------------- #

  tt_sl: 
    processes:
      - procs.tt_sl
    keys: 
      - /TTtoLNu2Q
      - /TTtoLNu2Q_ext1
    dest: tt.py

  tt_dl: 
    processes:
      - procs.tt_dl
    keys: 
      - /TTto2L2Nu
      - /TTto2L2Nu_ext1
    dest: tt.py

  tt_fh: 
    processes: 
      - procs.tt_fh
    keys: 
      - /TTto4Q
      - /TTto4Q_ext1
    dest: tt.py

  # -------------------------------------------------- #
  # ----------------------- ST ----------------------- #
  # -------------------------------------------------- #

  # single top
  
  st_tchannel_t: 
    processes: 
      - procs.st_tchannel_t
    keys: 
      - /ST_t-channel_top_4f_InclusiveDecays
    dest: st.py

  st_tchannel_tbar: 
    processes:
      - procs.st_tchannel_tbar
    keys: 
      - /ST_t-channel_antitop_4f_InclusiveDecays
    dest: st.py


  # -------------------------------------------------- #
  # ----------------------- TW ----------------------- #
  # -------------------------------------------------- #

  st_tw_t_sl: 
    processes:
      - procs.st_twchannel_t
    keys: 
      - /ST_tW_top_LNu2Q
      - /ST_tW_top_LNu2Q_ext1
    dest: st.py

  st_tw_t_dl: 
    processes:
      - procs.st_twchannel_t
    keys: 
      - /ST_tW_top_2L2Nu
      - /ST_tW_top_2L2Nu_ext1
    dest: st.py

  st_tw_t_fh: 
    processes:
      - procs.st_twchannel_t
    keys: 
      - /ST_tW_top_4Q
      - /ST_tW_top_4Q_ext1
    dest: st.py

  # --------------- t~w --------------- #

  st_tw_tb_sl: 
    processes:
      - procs.st_twchannel_tbar
    keys: 
      - /ST_tW_antitop_LNu2Q
      - /ST_tW_antitop_LNu2Q_ext1
    dest: st.py

  st_tw_tb_dl: 
    processes:
      - procs.st_twchannel_tbar
    keys: 
      - /ST_tW_antitop_2L2Nu
      - /ST_tW_antitop_2L2Nu_ext1
    dest: st.py

  st_tw_tb_fh: 
    processes:
      - procs.st_twchannel_tbar
    keys: 
      - /ST_tW_antitop_4Q
      - /ST_tW_antitop_4Q_ext1
    dest: st.py

  # -------------------------------------------------- #
  # ------------------- SIGNAL ----------------------- #
  # -------------------------------------------------- #

  h_ggf_tautau_prod_cp_even_sm:
    processes:
      - procs.h_ggf_tautau
    keys:
      - /GluGluHToTauTau_M125
    aux:
      is_signal: True
    dest: signal.py

  h_ggf_tautau_uncorrelated_filter:
    processes:
      - procs.h_ggf_tautau
    keys:
      - /GluGluHTo2Tau_UncorrelatedDecay_Filtered
    aux:
      is_signal: True
    dest: signal.py