# yaml file to produce the datasets for a campaign
# DATASET_NAME :
#   id :
#   processes :
#     - bla1
#     - bla2
#   keys :
#     - foo1
#     - foo2
#   n_files : CALC
#   n_events : CALC
#   destination : FILENAME


# name of the campaign to be created
campaign: run3_2022_postEE_nano_tau_v14
# path of the nanoaod samples
store_path: /eos/cms/store/group/phys_higgs/HLepRare/skim_2024_v1/Run3_2022EE
# era
era: 2022
nanoaod: 14
campaign_id: 202214101

datasets_info: 
  # -------------------------------------------------- #
  # ---------------------- DATA ---------------------- #
  # -------------------------------------------------- #

  # tau dataset

  data_tau_postEE_E:
    id: 11
    is_data: True
    processes:
      - procs.data_tau
    keys:
      - /Tau_Run2022E
    n_files: CALC
    n_events: CALC
    aux:
      era: E
      require_triggers:
        - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
        - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py

  data_tau_postEE_F:
    id: 12
    is_data: True
    processes:
      - procs.data_tau
    keys:
      - /Tau_Run2022F
    n_files: CALC
    n_events: CALC
    aux:
      era: F
      require_triggers:
        - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
        - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py


  # -------------------------------------------------- #
  # ----------------------- DY ----------------------- #
  # -------------------------------------------------- #

  dy_lep:
    id: 21
    is_data: False
    processes:
      - procs.dy_lep
    keys:
      - /DYto2L_M-50_amcatnloFXFX
    n_files: CALC
    n_events: CALC
    dest: ewk.py


  # -------------------------------------------------- #
  # ----------------------- WJ ----------------------- #
  # -------------------------------------------------- #

  wj_incl:
    id: 31
    is_data: False
    processes:
      - procs.wj
    keys:
      - /WtoLNu_amcatnloFXFX
    n_files: CALC
    n_events: CALC
    dest: ewk.py


  # -------------------------------------------------- #
  # ---------------------- TOP ----------------------- #
  # -------------------------------------------------- #

  # ttbar
  
  tt_sl: 
    id: 101
    is_data: False    
    processes:
      - procs.tt_sl
    keys: 
      - /TTtoLNu2Q
      - /TTtoLNu2Q_ext1
    n_files: CALC
    n_events: CALC
    dest: top.py

  tt_dl: 
    id: 102
    is_data: False
    processes:
      - procs.tt_dl
    keys: 
      - /TTTo2L2Nu
      - /TTto2L2Nu_ext1
    n_files: CALC
    n_events: CALC
    dest: top.py

  tt_fh: 
    id: 103
    is_data: False
    processes: 
      - procs.tt_fh
    keys: 
      - /TTto4Q
      - /TTto4Q_ext1
    n_files: CALC
    n_events: CALC
    dest: top.py


  # single top
  
  st_tchannel_t: 
    id: 201
    is_data: False
    processes: 
      - procs.st_tchannel_t
    keys: 
      - /ST_t-channel_top_4f_InclusiveDecays
    n_files: CALC
    n_events: CALC
    dest: top.py

  st_tchannel_tbar: 
    id: 202
    is_data: False
    processes:
      - procs.st_tchannel_tbar
    keys: 
      - /ST_t-channel_antitop_4f_InclusiveDecays
    n_files: CALC
    n_events: CALC
    dest: top.py

  # tw

  st_tw_t_sl: 
    id: 301
    is_data: False
    processes:
      - procs.st_twchannel_t_sl
    keys: 
      - /ST_tW_top_LNu2Q
      - /ST_tW_top_LNu2Q_ext1
    n_files: CALC
    n_events: CALC
    dest: top.py

  st_tw_t_dl: 
    id: 302
    is_data: False
    processes:
      - procs.st_twchannel_t_dl
    keys: 
      - /ST_tW_top_2L2Nu
      - /ST_tW_top_2L2Nu_ext1
    n_files: CALC
    n_events: CALC
    dest: top.py

  st_tw_t_fh: 
    id: 303
    is_data: False
    processes:
      - procs.st_twchannel_t_fh
    keys: 
      - /ST_tW_top_4Q
      - /ST_tW_top_4Q_ext1
    n_files: CALC
    n_events: CALC
    dest: top.py


  # t~w

  st_tw_tb_sl: 
    id: 401
    is_data: False
    processes:
      - procs.st_twchannel_tbar_sl
    keys: 
      - /ST_tW_antitop_LNu2Q
      - /ST_tW_antitop_LNu2Q_ext1
    n_files: CALC
    n_events: CALC
    dest: top.py

  st_tw_tb_dl: 
    id: 402
    is_data: False
    processes:
      - procs.st_twchannel_tbar_dl
    keys: 
      - /ST_tW_antitop_2L2Nu
      - /ST_tW_antitop_2L2Nu_ext1
    n_files: CALC
    n_events: CALC
    dest: top.py

  st_tw_tb_fh: 
    id: 403
    is_data: False
    processes:
      - procs.st_twchannel_tbar_fh
    keys: 
      - /ST_tW_antitop_4Q
      - /ST_tW_antitop_4Q_ext1
    n_files: CALC
    n_events: CALC
    dest: top.py


  # -------------------------------------------------- #
  # ------------------- SIGNAL ----------------------- #
  # -------------------------------------------------- #

  h_ggf_tautau:
    id: 1111
    is_data: False
    processes:
      - procs.h_ggf_tautau
    keys:
      - /GluGluHToTauTau_M125
    n_files: CALC
    n_events: CALC
    aux:
      is_signal: True
    dest: signal.py