# yaml file to produce the datasets for a campaign
# DATASET_NAME :
#   id :
#   processes :
#     - bla1
#     - bla2
#   keys :
#     - foo1
#     - foo2
#   n_files : CALC (automatic)
#   n_events : CALC (automatic)
#   destination : FILENAME


# name of the campaign to be created
campaign: run3_2023_postBPix_nano_cp_tau_v12
# path of the nanoaod samples
store_path: /eos/cms/store/group/phys_higgs/HLepRare/skim_2024_v1/Run3_2023BPix
# era
era: 2023
nanoaod: 12
postfix: postBPix
# year (YR) version (nanoaod) UniqueNo (ZZ)
campaign_id: 231202

datasets_info: 
  # -------------------------------------------------- #
  # ---------------------- DATA ---------------------- #
  # -------------------------------------------------- #

  # ------------ tau dataset -------------- #

  data_tau_D:
    processes:
      - procs.data_tau
    keys:
      - /Tau_Run2023D_v1
      - /Tau_Run2023D_v2
    aux:
      era: D
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py

  # ------------ mu dataset ------------- #

  data_mu0_D:
    processes:
      - procs.data_mu
    keys:
      - /Muon0_Run2023D_v1
    aux:
      era: D
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py

  data_mu1_D:
    processes:
      - procs.data_mu
    keys:
      - /Muon1_Run2023D_v1
    aux:
      era: D
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py

  # ------------- e dataset -------------- #

  data_e0_D: 
    processes:
      - procs.data_e
    keys:
      - /EGamma0_Run2023D_v1
      - /EGamma0_Run2023D_v2
    aux:
      era: D
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py


  data_e1_D: 
    processes:
      - procs.data_e
    keys:
      - /EGamma1_Run2023D_v1
      - /EGamma1_Run2023D_v2
    aux:
      era: D
      #require_triggers:
      #  - DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1
      #  - DoubleTightChargedIsoPFTauHPS35_Trk1_eta2p1
    dest: data.py

  # -------------------------------------------------- #
  # ----------------------- DY ----------------------- #
  # -------------------------------------------------- #

  dy_lep_m50:
    processes:
      - procs.dy_lep_m50
    keys:
      - /DYto2L_M-50_amcatnloFXFX
    dest: dy.py

  dy_lep_m10to50:
    processes:
      - procs.dy_lep_m10to50
    keys:
      - /DYto2L_M-10to50_madgraphMLM
    dest: dy.py

  dy_lep_0j:
    processes:
      - procs.dy_lep_m50_0j
    keys:
      - /DYto2L_M-50_0J_amcatnloFXFX
    dest: dy.py

  dy_lep_1j:
    processes:
      - procs.dy_lep_m50_1j
    keys:
      - /DYto2L_M-50_1J_amcatnloFXFX
    dest: dy.py

  dy_lep_2j:
    processes:
      - procs.dy_lep_m50_2j
    keys:
      - /DYto2L_M-50_2J_amcatnloFXFX
    dest: dy.py


  # -------------------------------------------------- #
  # ----------------------- WJ ----------------------- #
  # -------------------------------------------------- #

  wj_incl:
    processes:
      - procs.w_lnu
    keys:
      - /WtoLNu_madgraphMLM
    dest: wj.py

  # -------------------------------------------------- #
  # ----------------------- VV ----------------------- #
  # -------------------------------------------------- #

  ww:
    processes:
      - procs.ww
    keys:
      - /WW
    dest: vv.py
    
  wz:
    processes:
      - procs.wz
    keys:
      - /WZ
    dest: vv.py

  zz:
    processes:
      - procs.zz
    keys:
      - /ZZ
    dest: vv.py


  # -------------------------------------------------- #
  # ----------------------- TT ----------------------- #
  # -------------------------------------------------- #

  tt_sl: 
    processes:
      - procs.tt_sl
    keys: 
      - /TTtoLNu2Q
    dest: tt.py

  tt_dl: 
    processes:
      - procs.tt_dl
    keys: 
      - /TTTo2L2Nu
    dest: tt.py

  tt_fh: 
    processes: 
      - procs.tt_fh
    keys: 
      - /TTto4Q
    dest: tt.py

  # -------------------------------------------------- #
  # ----------------------- ST ----------------------- #
  # -------------------------------------------------- #

  # single top
  
  #st_tchannel_t: 
  #  processes: 
  #    - procs.st_tchannel_t
  #  keys: 
  #    - /ST_t-channel_top_4f_InclusiveDecays
  #  dest: st.py

  #st_tchannel_tbar: 
  #  processes:
  #    - procs.st_tchannel_tbar
  #  keys: 
  #    - /ST_t-channel_antitop_4f_InclusiveDecays
  #  dest: st.py


  # -------------------------------------------------- #
  # ----------------------- TW ----------------------- #
  # -------------------------------------------------- #

  st_tw_t_sl: 
    processes:
      - procs.st_twchannel_t_sl
    keys: 
      - /ST_tW_top_LNu2Q
    dest: st.py

  st_tw_t_dl: 
    processes:
      - procs.st_twchannel_t_dl
    keys: 
      - /ST_tW_top_2L2Nu
    dest: st.py

  st_tw_t_fh: 
    processes:
      - procs.st_twchannel_t_fh
    keys: 
      - /ST_tW_top_4Q
    dest: st.py


  # t~w

  st_tw_tb_sl: 
    processes:
      - procs.st_twchannel_tbar_sl
    keys: 
      - /ST_tW_antitop_LNu2Q
    dest: st.py

  st_tw_tb_dl: 
    processes:
      - procs.st_twchannel_tbar_dl
    keys: 
      - /ST_tW_antitop_2L2Nu
    dest: st.py

  st_tw_tb_fh: 
    processes:
      - procs.st_twchannel_tbar_fh
    keys: 
      - /ST_tW_antitop_4Q
    dest: st.py


  # -------------------------------------------------- #
  # ------------------- SIGNAL ----------------------- #
  # -------------------------------------------------- #

  h_ggf_tautau_prod_cp_even_sm:
    processes:
      - procs.h_ggf_tautau
    keys:
      - /GluGluHToTauTau_M125
    aux:
      is_signal: True
    dest: signal.py


  h_ggf_tautau_flat:
    processes:
      - procs.h_ggf_tautau
    keys:
      - /GluGluHTo2Tau_UncorrelatedDecay_Filtered
    aux:
      is_signal: True
    dest: signal.py